In [6]:
import pygame
import numpy
import sys

ROWS = 6
COLUMNS = 7

BLUE = (0, 0, 225)
BLACK = (0, 0, 0)
RED = (230, 0, 0)
YELLOW = (0, 240, 0)

def initialize_board():
    game_board = np.zeros((ROWS, COLUMNS))
    return game_board

def drop_piece(board, row, column, piece):
    board[row][column] = piece
    
def get_open_row(board, column):
    for row in range(Rows):
        if board[row][column] == 0:
            return row
def display_board(board):
    for column in range(COLUMNS):
        for row in range(ROWS):
            pygame.draw.rect(game_screen, BLUE, (column * LOCATION_SIZE, row * LOCATION_SIZE, LOCATION_SIZE + 100, LOCATION_SIZE))
            pygame.draw.circle(game_screen, BLACK, (column * LOCATION_SIZE + LOCATION_SIZE / 2, row * LOCATION_SIZE + LOCATION_SIZE / 2), LOCATION_SIZE / 2)
            
    for column in range(COLUMNS):
        for row in range(ROWS):
            if board[row][column] == 1:
                pygame.draw.circle(game_screen, RED, (column * LOCATION_SIZE + LOCATION_SIZE / 2, SCREEN_HEIGHT - (row * LOCATION_SIZE + LOCATION_SIZE / 2), LOCATION_SIZE / 2))
                
            else:
                pygame.draw.circle(game_screen, YELLOW, (column * LOCATION_SIZE + LOCATION_SIZE / 2, SCREEN_HEIGHT - (row * LOCATION_SIZE + LOCATION_SIZE / 2), LOCATION_SIZE / 2))
                    
    pygame.display.update()
            
        
def print_board(game_board):
    print(numpy.flip(game_board, 0))
        
game_board = initialize_board()
print_board(game_board)
turn = 0
game_over = False

pygame.init()

SCREEN_LENGTH = 900
SCREEN_HEIGHT = 700
LOCATION_SIZE = 100

game_screen = pygame.display.set_mode((SCREEN_LENGTH, SCREEN_HEIGHT))




while not game_over:
    if event.type == pygame.QUIT:
        game_over = True
        
    if event.type == pygame.MOUSEMOTION:
        pygame.draw.rect(game_screen, BLACK, (0, 0, SCREEN_LENGTH, LOCATION_SIZE))
        position = event.pos[0]
        if (turn % 2 == 1):
            pygame.draw.circle(game_screen, RED, (position, LOCATION_SIZE))
            
        else:
            pygame.draw.circle(game_screen, YELLOW, (position, LOCATION_SIZE))
    
    pygame.display.update()
    
    if event.type == pygame.MOUSEBUTTONDOWN:
        pygame.draw.rect(game_screen, BLACK, (0, 0, SCREEN_LENGTH, LOCATION_SIZE))
        
        if (turn % 2 == 1):
            position = event.pos[0]
            column = position / (LOCATION_SIZE + 100)
            
            row = get_open_row(board, column)
            drop_piece(board, row, column, 1)
            
            if winner_decided(board, 1):
                winning_message = myfont.render("Player 1 wins!", 1, RED)
                game_screen.blit(winning_message, (100, 50))
                game_over = True
                
        else:
            position = event.pos[0]
            column = position / (LOCATION_SIZE + 100)
            
            row = get_open_row(board, column)
            drop_piece(board, row, column, 2)
            
            if winner_decided(board, 2):
                winning_message = myfont.render("Player 2 wins!", 1, Yellow)
                game_screen.blit(winning_message, (100, 50))
                game_over = True
                
        
    display_board(board)
    
    
    turn += 1
        


pygame.quit()

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


NameError: name 'pyygame' is not defined

In [4]:
import numpy as np
import pygame
import sys
import math
 
BLUE = (0,0,230)
BLACK = (0,0,0)
RED = (255,0,0)
YELLOW = (255,255,0)
 
ROW_COUNT = 6
COLUMN_COUNT = 7
 
def create_board():
    board = np.zeros((ROW_COUNT,COLUMN_COUNT))
    return board
 
def drop_piece(board, row, col, piece):
    board[row][col] = piece
 
def is_valid_location(board, col):
    return board[ROW_COUNT-1][col] == 0
 
def get_next_open_row(board, col):
    for r in range(ROW_COUNT):
        if board[r][col] == 0:
            return r
 
def print_board(board):
    print(np.flip(board, 0))
 
def winning_move(board, piece):
    # Check horizontal locations for win
    for c in range(COLUMN_COUNT-3):
        for r in range(ROW_COUNT):
            if board[r][c] == piece and board[r][c+1] == piece and board[r][c+2] == piece and board[r][c+3] == piece:
                return True
 
    # Check vertical locations for win
    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT-3):
            if board[r][c] == piece and board[r+1][c] == piece and board[r+2][c] == piece and board[r+3][c] == piece:
                return True
 
    # Check positively sloped diaganols
    for c in range(COLUMN_COUNT-3):
        for r in range(ROW_COUNT-3):
            if board[r][c] == piece and board[r+1][c+1] == piece and board[r+2][c+2] == piece and board[r+3][c+3] == piece:
                return True
 
    # Check negatively sloped diaganols
    for c in range(COLUMN_COUNT-3):
        for r in range(3, ROW_COUNT):
            if board[r][c] == piece and board[r-1][c+1] == piece and board[r-2][c+2] == piece and board[r-3][c+3] == piece:
                return True
 
def draw_board(board):
    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT):
            pygame.draw.rect(screen, BLUE, (c*SQUARESIZE, r*SQUARESIZE+SQUARESIZE, SQUARESIZE, SQUARESIZE))
            pygame.draw.circle(screen, BLACK, (int(c*SQUARESIZE+SQUARESIZE/2), int(r*SQUARESIZE+SQUARESIZE+SQUARESIZE/2)), RADIUS)
     
    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT):      
            if board[r][c] == 1:
                pygame.draw.circle(screen, RED, (int(c*SQUARESIZE+SQUARESIZE/2), height-int(r*SQUARESIZE+SQUARESIZE/2)), RADIUS)
            elif board[r][c] == 2: 
                pygame.draw.circle(screen, YELLOW, (int(c*SQUARESIZE+SQUARESIZE/2), height-int(r*SQUARESIZE+SQUARESIZE/2)), RADIUS)
    pygame.display.update()
 
 
board = create_board()
print_board(board)
game_over = False
turn = 0
 
#initalize pygame
pygame.init()
 
#define our screen size
SQUARESIZE = 100
 
#define width and height of board
width = COLUMN_COUNT * SQUARESIZE
height = (ROW_COUNT+1) * SQUARESIZE
 
size = (width, height)
 
RADIUS = int(SQUARESIZE/2 - 5)
 
screen = pygame.display.set_mode(size)
#Calling function draw_board again
draw_board(board)
pygame.display.update()
 
myfont = pygame.font.SysFont("monospace", 75)
 
while not game_over:
 
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()
 
        if event.type == pygame.MOUSEMOTION:
            pygame.draw.rect(screen, BLACK, (0,0, width, SQUARESIZE))
            posx = event.pos[0]
            if turn == 0:
                pygame.draw.circle(screen, RED, (posx, int(SQUARESIZE/2)), RADIUS)
            else: 
                pygame.draw.circle(screen, YELLOW, (posx, int(SQUARESIZE/2)), RADIUS)
        pygame.display.update()
 
        if event.type == pygame.MOUSEBUTTONDOWN:
            pygame.draw.rect(screen, BLACK, (0,0, width, SQUARESIZE))
            #print(event.pos)
            # Ask for Player 1 Input
            if turn == 0:
                posx = event.pos[0]
                col = int(math.floor(posx/SQUARESIZE))
 
                if is_valid_location(board, col):
                    row = get_next_open_row(board, col)
                    drop_piece(board, row, col, 1)
 
                    if winning_move(board, 1):
                        label = myfont.render("Player 1 wins!!", 1, RED)
                        screen.blit(label, (40,10))
                        game_over = True
 
 
            # # Ask for Player 2 Input
            else:               
                posx = event.pos[0]
                col = int(math.floor(posx/SQUARESIZE))
 
                if is_valid_location(board, col):
                    row = get_next_open_row(board, col)
                    drop_piece(board, row, col, 2)
 
                    if winning_move(board, 2):
                        label = myfont.render("Player 2 wins!!", 1, YELLOW)
                        screen.blit(label, (40,10))
                        game_over = True
 
            print_board(board)
            draw_board(board)
 
            turn += 1
            turn = turn % 2
 
            if game_over:
                pygame.time.wait(3000)
            
pygame.quit()

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2.