In [1]:
import pygame
import numpy
import sys
import math

ROWS = 6
COLUMNS = 7

BLUE = (0, 0, 225)
BLACK = (0, 0, 0)
RED = (230, 0, 0)
YELLOW = (0, 240, 0)
SCREEN_LENGTH = 700
SCREEN_HEIGHT = 600
LOCATION_SIZE = 100
RADIUS = int(LOCATION_SIZE / 2 - 5)

game_screen = pygame.display.set_mode((SCREEN_LENGTH, SCREEN_HEIGHT))

def initialize_board():
    game_board = numpy.zeros((ROWS, COLUMNS))
    return game_board

def drop_piece(game_board, row, column, piece):
    game_board[row][column] = piece
    
def get_open_row(game_board, column):
    for row in range(ROWS):
        if game_board[row][column] == 0:
            return row
        
def is_valid_location(game_board, column):
    return game_board[ROWS-1][column] == 0

def winning_move(game_board, piece):
    """
    This method was used from a source online.
    """
    #Check horizontal locations for win
    for column in range(COLUMNS-3):
        for row in range(ROWS):
            if game_board[row][column] == piece and game_board[row][column + 1] == piece and game_board[row][column + 2] == piece and game_board[row][column + 3] == piece:
                return True
 
    # Check vertical locations for win
    for column in range(COLUMNS):
        for r in range(ROWS - 3):
            if game_board[row][column] == piece and game_board[row + 1][column] == piece and game_board[row + 2][column] == piece and game_board[row + 3][column] == piece:
                return True
 
    # Check positively sloped diaganols
    for column in range(COLUMNS - 3):
        for row in range(ROWS - 3):
            if game_board[row][column] == piece and game_board[row + 1][column + 1] == piece and game_board[row + 2][column + 2] == piece and game_board[row + 3][column + 3] == piece:
                return True
 
    # Check negatively sloped diaganols
    for column in range(COLUMNS - 3):
        for row in range(3, ROWS):
            if game_board[row][column] == piece and game_board[row - 1][column + 1] == piece and game_board[row - 2][column + 2] == piece and game_board[row - 3][column + 3] == piece:
                return True
def display_board(game_board):
    for column in range(COLUMNS):
        for row in range(ROWS):
            pygame.draw.rect(game_screen, BLUE, (column  * LOCATION_SIZE, row * LOCATION_SIZE + LOCATION_SIZE, LOCATION_SIZE, LOCATION_SIZE))
            pygame.draw.circle(game_screen, BLACK, (int(column * LOCATION_SIZE + LOCATION_SIZE / 2), int(row * LOCATION_SIZE + LOCATION_SIZE + LOCATION_SIZE / 2)), RADIUS)
            
    for column in range(COLUMNS):
        for row in range(ROWS):
            if game_board[row][column] == 1:
                pygame.draw.circle(game_screen, RED, (int(column * LOCATION_SIZE + LOCATION_SIZE / 2), SCREEN_HEIGHT - int(row * LOCATION_SIZE + LOCATION_SIZE / 2)), RADIUS)
            elif game_board[row][column]:
                pygame.draw.circle(game_screen, YELLOW, (int(column * LOCATION_SIZE + LOCATION_SIZE / 2), SCREEN_HEIGHT - int(row * LOCATION_SIZE + LOCATION_SIZE / 2)), RADIUS)
                    
    pygame.display.update()
            
        
def print_board(game_board):
    print(numpy.flip(game_board, 0))
        
game_board = initialize_board()
display_board(game_board)
turn = 0
game_over = False
player_one_wins = 0
player_two_wins = 0

pygame.init()
message_font = pygame.font.SysFont("Comic Sans", 70)


while not game_over:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()
 
        if event.type == pygame.MOUSEMOTION:
            pygame.draw.rect(game_screen, BLACK, (0,0, SCREEN_LENGTH, LOCATION_SIZE))
            posx = event.pos[0]
            if turn == 0:
                pygame.draw.circle(game_screen, RED, (posx, int(LOCATION_SIZE/2)), RADIUS)
            else: 
                pygame.draw.circle(game_screen, YELLOW, (posx, int(LOCATION_SIZE/2)), RADIUS)
        pygame.display.update()
 
        if event.type == pygame.MOUSEBUTTONDOWN:
            pygame.draw.rect(game_screen, BLACK, (0,0, SCREEN_LENGTH, LOCATION_SIZE))
            if turn == 0:
                posx = event.pos[0]
                column = int(math.floor(posx/LOCATION_SIZE))
 
                if is_valid_location(game_board, column):
                    row = get_open_row(game_board, column)
                    drop_piece(game_board, row, column, 1)
 
                    if winning_move(game_board, 1):
                        winning_message = message_font.render("Player 1 wins!!", 1, RED)
                        game_screen.blit(winning_message, (40,10))
                        player_one_wins = player_one_wins + 1
                        game_over = True
 
 
            # # Ask for Player 2 Input
            else:               
                posx = event.pos[0]
                column = int(math.floor(posx/LOCATION_SIZE))
 
                if is_valid_location(game_board, column):
                    row = get_open_row(game_board, column)
                    drop_piece(game_board, row, column, 2)
 
                    if winning_move(game_board, 2):
                        winning_message = message_font.render("Player 2 wins!!", 1, YELLOW)
                        game_screen.blit(winning_message, (40,10))
                        player_two_wins = player_two_wins + 1
                        game_over = True
 
            print_board(game_board)
            display_board(game_board)
    
    
            turn += 1
            turn = turn % 2
        


pygame.quit()

pygame 2.5.2 (SDL 2.28.3, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 2. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 1. 1. 2. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 2. 0. 0.]
 [0. 0. 0. 1. 1. 2. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 1. 2. 0. 0.]
 [0. 0. 0. 1. 1. 2. 0.]]
[[0. 0. 0. 0. 0. 

NameError: name 'myfont' is not defined

In [2]:
import numpy as np
import pygame
import sys
import math
 
BLUE = (0,0,230)
BLACK = (0,0,0)
RED = (255,0,0)
YELLOW = (255,255,0)
 
ROW_COUNT = 6
COLUMN_COUNT = 7
 
def create_board():
    board = np.zeros((ROW_COUNT,COLUMN_COUNT))
    return board
 
def drop_piece(board, row, col, piece):
    board[row][col] = piece
 
def is_valid_location(board, col):
    return board[ROW_COUNT-1][col] == 0
 
def get_next_open_row(board, col):
    for r in range(ROW_COUNT):
        if board[r][col] == 0:
            return r
 
def print_board(board):
    print(np.flip(board, 0))
 
def winning_move(board, piece):
    # Check horizontal locations for win
    for c in range(COLUMN_COUNT-3):
        for r in range(ROW_COUNT):
            if board[r][c] == piece and board[r][c+1] == piece and board[r][c+2] == piece and board[r][c+3] == piece:
                return True
 
    # Check vertical locations for win
    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT-3):
            if board[r][c] == piece and board[r+1][c] == piece and board[r+2][c] == piece and board[r+3][c] == piece:
                return True
 
    # Check positively sloped diaganols
    for c in range(COLUMN_COUNT-3):
        for r in range(ROW_COUNT-3):
            if board[r][c] == piece and board[r+1][c+1] == piece and board[r+2][c+2] == piece and board[r+3][c+3] == piece:
                return True
 
    # Check negatively sloped diaganols
    for c in range(COLUMN_COUNT-3):
        for r in range(3, ROW_COUNT):
            if board[r][c] == piece and board[r-1][c+1] == piece and board[r-2][c+2] == piece and board[r-3][c+3] == piece:
                return True
 
def draw_board(board):
    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT):
            pygame.draw.rect(screen, BLUE, (c*SQUARESIZE, r*SQUARESIZE+SQUARESIZE, SQUARESIZE, SQUARESIZE))
            pygame.draw.circle(screen, BLACK, (int(c*SQUARESIZE+SQUARESIZE/2), int(r*SQUARESIZE+SQUARESIZE+SQUARESIZE/2)), RADIUS)
     
    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT):      
            if board[r][c] == 1:
                pygame.draw.circle(screen, RED, (int(c*SQUARESIZE+SQUARESIZE/2), height-int(r*SQUARESIZE+SQUARESIZE/2)), RADIUS)
            elif board[r][c] == 2: 
                pygame.draw.circle(screen, YELLOW, (int(c*SQUARESIZE+SQUARESIZE/2), height-int(r*SQUARESIZE+SQUARESIZE/2)), RADIUS)
    pygame.display.update()
 
 
board = create_board()
print_board(board)
game_over = False
turn = 0
 
#initalize pygame
pygame.init()
 
#define our screen size
SQUARESIZE = 100
 
#define width and height of board
width = COLUMN_COUNT * SQUARESIZE
height = (ROW_COUNT+1) * SQUARESIZE
 
size = (width, height)
 
RADIUS = int(SQUARESIZE/2 - 5)
 
screen = pygame.display.set_mode(size)
#Calling function draw_board again
draw_board(board)
pygame.display.update()
 
myfont = pygame.font.SysFont("monospace", 75)
 
while not game_over:
 
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()
 
        if event.type == pygame.MOUSEMOTION:
            pygame.draw.rect(screen, BLACK, (0,0, width, SQUARESIZE))
            posx = event.pos[0]
            if turn == 0:
                pygame.draw.circle(screen, RED, (posx, int(SQUARESIZE/2)), RADIUS)
            else: 
                pygame.draw.circle(screen, YELLOW, (posx, int(SQUARESIZE/2)), RADIUS)
        pygame.display.update()
 
        if event.type == pygame.MOUSEBUTTONDOWN:
            pygame.draw.rect(screen, BLACK, (0,0, width, SQUARESIZE))
            #print(event.pos)
            # Ask for Player 1 Input
            if turn == 0:
                posx = event.pos[0]
                col = int(math.floor(posx/SQUARESIZE))
 
                if is_valid_location(board, col):
                    row = get_next_open_row(board, col)
                    drop_piece(board, row, col, 1)
 
                    if winning_move(board, 1):
                        label = myfont.render("Player 1 wins!!", 1, RED)
                        screen.blit(label, (40,10))
                        game_over = True
 
 
            # # Ask for Player 2 Input
            else:               
                posx = event.pos[0]
                col = int(math.floor(posx/SQUARESIZE))
 
                if is_valid_location(board, col):
                    row = get_next_open_row(board, col)
                    drop_piece(board, row, col, 2)
 
                    if winning_move(board, 2):
                        label = myfont.render("Player 2 wins!!", 1, YELLOW)
                        screen.blit(label, (40,10))
                        game_over = True
 
            print_board(board)
            draw_board(board)
 
            turn += 1
            turn = turn % 2
 
            if game_over:
                pygame.time.wait(3000)
            
pygame.quit()

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0.

In [1]:
import pygame
import sys
import time
import random

pygame.init()

# Constants
WIDTH, HEIGHT = 800, 800

# Create the game window
WIN = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Menu")

# Menu variables
menu_font = pygame.font.SysFont("comicsans", 50)
menu_items = ["Snake", "Connect Four", "Pong", "Quit"]
selected_item = 0  # Index of the selected menu item
class SnakeGame:
    def __init__(self):
        pygame.init()
        self.window_size = (500, 500)
        self.surface = pygame.display.set_mode(self.window_size)
        pygame.display.set_caption('Snake Game')
        self.clock = pygame.time.Clock()

        # Create zig-zag background
        self.create_zigzag_background()

        # Load snake block image
        self.snake_block = pygame.image.load('block.jpg')
        self.snake_block = pygame.transform.scale(self.snake_block, (10, 10))

        # Load images
        self.apple_block = pygame.Surface((10, 10))
        self.apple_block.fill((255, 0, 0))  # Apple color (red)

        # Snake attributes
        self.snake_pos = [100, 50]
        self.snake_body = [[100, 50], [90, 50], [80, 50], [70, 50], [60, 50]]
        self.direction = 'RIGHT'
        self.change_to = self.direction
        self.speed = 15

        # Apple attributes
        self.apple_pos = [random.randrange(1, (self.window_size[0] // 10)) * 10,
                          random.randrange(1, (self.window_size[1] // 10)) * 10]

        # Score
        self.score = 0
        self.font = pygame.font.Font(None, 36)

    def create_zigzag_background(self):
    # Create a surface for the background
        self.background = pygame.Surface(self.window_size)
        self.background.fill((0, 100, 0))  # Dark green

    # Draw light green zig-zag lines
    def draw_elements(self):
        self.surface.blit(self.background, (0, 0))

        # Draw snake and apple
        for pos in self.snake_body:
            self.surface.blit(self.snake_block, pos)
        self.surface.blit(self.apple_block, self.apple_pos)

        # Display score
        score_text = self.font.render(f'Score: {self.score}', True, (255, 255, 255))
        self.surface.blit(score_text, (10, 10))

        pygame.display.flip()

    def run_game(self):
        while True:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:  # Handle the window close event
                    pygame.quit()
                    quit()
                if event.type == pygame.KEYDOWN:
                    if event.key == pygame.K_UP:
                        self.change_to = 'UP'
                    elif event.key == pygame.K_DOWN:
                        self.change_to = 'DOWN'
                    elif event.key == pygame.K_LEFT:
                        self.change_to = 'LEFT'
                    elif event.key == pygame.K_RIGHT:
                        self.change_to = 'RIGHT'

            # Change the direction according to the pressed key
            if self.change_to == 'UP' and not self.direction == 'DOWN':
                self.direction = 'UP'
            if self.change_to == 'DOWN' and not self.direction == 'UP':
                self.direction = 'DOWN'
            if self.change_to == 'LEFT' and not self.direction == 'RIGHT':
                self.direction = 'LEFT'
            if self.change_to == 'RIGHT' and not self.direction == 'LEFT':
                self.direction = 'RIGHT'

            # Move the snake
            if self.direction == 'UP':
                self.snake_pos[1] -= 10
            if self.direction == 'DOWN':
                self.snake_pos[1] += 10
            if self.direction == 'LEFT':
                self.snake_pos[0] -= 10
            if self.direction == 'RIGHT':
                self.snake_pos[0] += 10

            if (
                self.snake_pos[0] < 0 or
                self.snake_pos[0] > self.window_size[0] - 10 or
                self.snake_pos[1] < 0 or
                self.snake_pos[1] > self.window_size[1] - 10 or
                self.snake_pos in self.snake_body[1:]
            ):
                pygame.quit()
                quit()

            # Check if the snake has eaten the apple
            if self.snake_pos == self.apple_pos:
                self.apple_pos = [random.randrange(1, (self.window_size[0] // 10)) * 10,
                                  random.randrange(1, (self.window_size[1] // 10)) * 10]
                self.score += 1
                self.snake_body.append(list(self.snake_pos))  # Use list() to create a copy

            else:
                # Remove the last segment of the snake
                self.snake_body.pop()

            # Add a new segment to the snake
            self.snake_body.insert(0, list(self.snake_pos))

            # Draw the game elements
            self.draw_elements()

            # Control the speed of the game
            self.clock.tick(self.speed)

def run_snake_game():
    game = SnakeGame()
    game.run_game()

# Main menu loop
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_DOWN:
                selected_item = (selected_item + 1) % len(menu_items)
            elif event.key == pygame.K_UP:
                selected_item = (selected_item - 1) % len(menu_items)
            elif event.key == pygame.K_RETURN:
                if menu_items[selected_item] == "Snake":
                    run_snake_game()
                elif menu_items[selected_item] == "Connect Four":
                    pygame.quit()
                    # Add the Connect Four game class here
                elif menu_items[selected_item] == "Pong":
                    pygame.quit()
                    # Add the Pong game class here
                elif menu_items[selected_item] == "Quit":
                    pygame.quit()
                    sys.exit()

    # Display the menu
    WIN.fill((0, 0, 0))  # Black background
    for i, item in enumerate(menu_items):
        color = (255, 255, 255) if i == selected_item else (128, 128, 128)
        text = menu_font.render(item, True, color)
        x = (WIN.get_width() - text.get_width()) // 2
        y = (i + 1) * 100
        WIN.blit(text, (x, y))
    pygame.display.update()

pygame 2.5.2 (SDL 2.28.3, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html


error: display Surface quit

In [ ]:
class ConnectFour:
    def __init__(self, rows, columns, screen_length, screen_height, location_size, radius):
        self.rows = rows
        self.columns = columns
        self.screen_length = screen_length
        self.screen_height = screen_height
        self.location_size = location_size
        self.radius = radius
        self.game_screen = pygame.display.set_mode((screen_length, screen_height))
        self.game_board = self.initialize_board()
        self.turn = 0
        self.game_over = False
        self.player_one_wins = 0
        self.player_two_wins = 0
        self.message_font = pygame.font.SysFont("Comic Sans", 70)

    def initialize_board(self):
        return numpy.zeros((self.rows, self.columns))

    def drop_piece(self, row, column, piece):
        self.game_board[row][column] = piece

    def get_open_row(self, column):
        for row in range(self.rows):
            if self.game_board[row][column] == 0:
                return row

    def is_valid_location(self, column):
        return self.game_board[self.rows - 1][column] == 0

    def winning_move(self, piece):
        # Implementation remains unchanged

    def display_board(self):
        # Implementation remains unchanged

    def print_board(self):
        print(numpy.flip(self.game_board, 0))

    def run_game(self):
        while not self.game_over:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    sys.exit()

                if event.type == pygame.MOUSEMOTION:
                    # Implementation remains unchanged

                pygame.display.update()

                if event.type == pygame.MOUSEBUTTONDOWN:
                    # Implementation remains unchanged

                    print_board(self.game_board)
                    display_board(self.game_board)

                    self.turn += 1
                    self.turn %= 2

        pygame.quit()